services:
  sonarqube-mcp:
    build: .
    environment:
      - SONARQUBE_URL=http://host.docker.internal:8088
      - SONARQUBE_TOKEN=squ_f5d437fc56b7a7b8f1654a7f3515511d1e16581d
      - SONARQUBE_USERNAME=admin
      - SONARQUBE_PASSWORD=admin
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - mcp-network
    # Override the default command to run the MCP server
    command: ["python", "mcp_server.py"]
    # Add extra hosts to ensure host.docker.internal works
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  mcp-network:
    driver: bridge