services:
  sonarqube-mcp:
    build: .
    environment:
      - SONARQUBE_URL=${SONARQUBE_URL:-http://host.docker.internal:8088}
      - SONARQUBE_TOKEN=${SONARQUBE_TOKEN}
      - SONARQUBE_USERNAME=${SONARQUBE_USERNAME}
      - SONARQUBE_PASSWORD=${SONARQUBE_PASSWORD}
    env_file:
      - .env.docker
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - mcp-network
    # Override the default command to run the MCP server
    command: ["python", "mcp_server.py"]

networks:
  mcp-network:
    driver: bridge